# This is a basic workflow to help you get started with Actions

name: Build-CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  frontend-lint-test-build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install node packages
        working-directory: ./frontend
        run: npm install
      - name: run frontend tests
        working-directory: ./frontend
        run: npm test
      - name: run frontend lint
        working-directory: ./frontend
        run: npm run lint
      - name: build frontend
        working-directory: ./frontend
        run: npm run build --if-present
  
  backend-lint-test-build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install node packages
        working-directory: ./backend
        run: npm install
      - name: create .env file
        working-directory: ./backend
        run: echo "${{ secrets.ENV_FILE }}" > .env
      - name: run backend tests
        working-directory: ./backend
        run: npm test
      - name: run backend lint
        working-directory: ./backend
        run: npm run lint
      - name: build backend
        working-directory: ./backend
        run: npm run build --if-present
